#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : menu-cache
Version  : 1.1.0
Release  : 3
URL      : https://github.com/lxde/menu-cache/archive/1.1.0.tar.gz
Source0  : https://github.com/lxde/menu-cache/archive/1.1.0.tar.gz
Summary  : Cache for freedesktop.org menu spec
Group    : Development/Tools
License  : LGPL-2.1
Requires: menu-cache-lib = %{version}-%{release}
Requires: menu-cache-libexec = %{version}-%{release}
Requires: menu-cache-license = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libfm-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libfm-extra)

%description
Libmenu-cache is a library creating and utilizing caches to speed up
the manipulation for freedesktop.org defined application menus.
It can be used as a replacement of libgnome-menu of gnome-menus.

%package dev
Summary: dev components for the menu-cache package.
Group: Development
Requires: menu-cache-lib = %{version}-%{release}
Provides: menu-cache-devel = %{version}-%{release}
Requires: menu-cache = %{version}-%{release}

%description dev
dev components for the menu-cache package.


%package lib
Summary: lib components for the menu-cache package.
Group: Libraries
Requires: menu-cache-libexec = %{version}-%{release}
Requires: menu-cache-license = %{version}-%{release}

%description lib
lib components for the menu-cache package.


%package libexec
Summary: libexec components for the menu-cache package.
Group: Default
Requires: menu-cache-license = %{version}-%{release}

%description libexec
libexec components for the menu-cache package.


%package license
Summary: license components for the menu-cache package.
Group: Default

%description license
license components for the menu-cache package.


%prep
%setup -q -n menu-cache-1.1.0
cd %{_builddir}/menu-cache-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579646338
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1579646338
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/menu-cache
cp %{_builddir}/menu-cache-1.1.0/COPYING %{buildroot}/usr/share/package-licenses/menu-cache/a222eb7a5344a5c487bd633a6eb5810028d5a74e
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/menu-cache/menu-cache.h
/usr/lib64/libmenu-cache.so
/usr/lib64/pkgconfig/libmenu-cache.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmenu-cache.so.3
/usr/lib64/libmenu-cache.so.3.2.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/menu-cache/menu-cache-gen
/usr/libexec/menu-cache/menu-cached

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/menu-cache/a222eb7a5344a5c487bd633a6eb5810028d5a74e
